[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_starter = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/jennifer/.config/solana/id.json"

[scripts]
test = "node tests/solanastarter.js"
