[features]
seeds = false
skip-lint = false
[programs.devnet]
solanastarter = "B85YcqVUBMK1Ba7K2jg7xmwXadJEMrRD6NKEXUdokeYc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/jennifer/.config/solana/id.json"

[scripts]
test = "node tests/solanastarter.js"
